export const CATEGORIES = [
  "Airsoft",
  "Alimentos",
  "Altinha",
  "Artes Marciais",
  "Arrancada",
  "Automotiva",
  "Badminton",
  "Baseball",
  "Basquete",
  "Batizado",
  "Beach Tennis",
  "Canoa Havaiana",
  "Casamento",
  "Ciclismo",
  "Corporativo",
  "Corrida",
  "Crossfit",
  "Dança",
  "Drones",
  "Ecommerce",
  "Ensaios",
  "Equestre",
  "Escalada Trilhas",
  "Esportes",
  "Evento Religioso",
  "Eventos",
  "Família",
  "Festas",
  "Flag Football",
  "Formaturas",
  "Futebol",
  "Futebol Americano",
  "Futebol de Areia",
  "Futevôlei",
  "Futsal",
  "Ginástica",
  "Golfe",
  "Grau",
  "Handebol",
  "Hipismo",
  "Hyrox",
  "Iatismo",
  "Imóveis",
  "Jiu-jítsu",
  "Jornalística",
  "Judô",
  "Kart",
  "Kite Surf",
  "Mergulho",
  "Moda",
  "Motociclismo",
  "Motocross",
  "Mountain Bike",
  "Muay Thai",
  "Natação",
  "Natureza",
  "Offroad",
  "Outros",
  "Padel",
  "Paintball",
  "Paraquedismo",
  "Passeio",
  "Patinação",
  "Pescaria",
  "Pets",
  "Pickleball",
  "Rodeio",
  "Rugby",
  "Skate",
  "Skimboard",
  "Subaquática",
  "Surf",
  "Teatro e Musicais",
  "Tênis",
  "Tênis de Mesa",
  "Treinamento Funcional",
  "Treinos",
  "Triathlon",
  "Trilhas",
  "Turismo",
  "Vôlei",
  "Voo Livre",
];

export const NotificationType = {
  INFO: "INFO",
  SUCCESS: "SUCCESS",
  WARNING: "WARNING",
  ERROR: "ERROR",
};
